/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.ijse.view;

import edu.ijse.Controller.IssueBookController;
import edu.ijse.dto.IssuebookDto;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class IssueBooks extends javax.swing.JFrame {
private IssueBookController issueBookController;
    /**
     * Creates new form IssueBooks
     */
       public IssueBooks() throws Exception {
        initComponents();
         IssueBookController issueBookcontroller = new IssueBookController();
        loadTable();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblissuebook = new javax.swing.JLabel();
        lblbookid = new javax.swing.JLabel();
        txtbid = new javax.swing.JTextField();
        lblmemberid = new javax.swing.JLabel();
        txtmid = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        lblissuedate = new javax.swing.JLabel();
        txtidate = new javax.swing.JTextField();
        lblreturndate = new javax.swing.JLabel();
        txtrdate = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblissuebook = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblissuebook.setFont(new java.awt.Font("Sitka Banner", 1, 24)); // NOI18N
        lblissuebook.setText("Issue Book");

        lblbookid.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblbookid.setText("Book ID ");

        txtbid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbidActionPerformed(evt);
            }
        });

        lblmemberid.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblmemberid.setText("Member ID");

        btnadd.setBackground(new java.awt.Color(204, 204, 204));
        btnadd.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnadd.setText("add");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnupdate.setBackground(new java.awt.Color(204, 204, 204));
        btnupdate.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btndelete.setBackground(new java.awt.Color(204, 204, 204));
        btndelete.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        lblissuedate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblissuedate.setText("Issue Date");

        txtidate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidateActionPerformed(evt);
            }
        });

        lblreturndate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblreturndate.setText("Return Date");

        tblissuebook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Bid", "Mid", "Idate", "Rdate"
            }
        ));
        jScrollPane1.setViewportView(tblissuebook);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblbookid)
                            .addComponent(lblmemberid)
                            .addComponent(lblissuedate)
                            .addComponent(lblreturndate))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtbid, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                .addComponent(txtmid))
                            .addComponent(txtidate, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addComponent(txtrdate)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(lblissuebook, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnadd)
                        .addGap(18, 18, 18)
                        .addComponent(btnupdate)
                        .addGap(18, 18, 18)
                        .addComponent(btndelete)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblissuebook, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblbookid)
                            .addComponent(txtbid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblmemberid)
                            .addComponent(txtmid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblissuedate)
                            .addComponent(txtidate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblreturndate)
                            .addComponent(txtrdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnadd)
                            .addComponent(btnupdate)
                            .addComponent(btndelete))))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtbidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbidActionPerformed

    private void txtidateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidateActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        addbook();// TODO add your handling code here:
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
      updatebook();  // TODO add your handling code here:
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        deletebook();// TODO add your handling code here:
    }//GEN-LAST:event_btndeleteActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnupdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblbookid;
    private javax.swing.JLabel lblissuebook;
    private javax.swing.JLabel lblissuedate;
    private javax.swing.JLabel lblmemberid;
    private javax.swing.JLabel lblreturndate;
    private javax.swing.JTable tblissuebook;
    private javax.swing.JTextField txtbid;
    private javax.swing.JTextField txtidate;
    private javax.swing.JTextField txtmid;
    private javax.swing.JTextField txtrdate;
    // End of variables declaration//GEN-END:variables

private void addbook(){
        try {
            IssuebookDto dto = new IssuebookDto(txtbid.getText(),  txtmid.getText(),txtrdate.getText(), txtidate.getText());
            String resp = issueBookController.add(dto);
            JOptionPane.showMessageDialog(this, resp);
            clearForm();
            loadTable();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error at save data");
        }

    }

    
    private void loadTable() {
         try {
            String columns[] = {" Bid",  "Mid","Rdate", "Idate"};
            DefaultTableModel dtm = new DefaultTableModel(columns, 0) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };
            tblissuebook.setModel(dtm);

            ArrayList<IssuebookDto> issuebookDtos = issueBookController.getAll();
            for (IssuebookDto dto : issuebookDtos) {
                Object[] rowData = {dto.getBid(),  dto.getMid(),dto.getRdate(), dto.getIdate()};
                dtm.addRow(rowData);
            }
        } catch (Exception e) {
        e.printStackTrace();
        }
    }
    
    private void clearForm() {
        txtbid.setText("");
        txtmid.setText("");
        txtrdate.setText("");
        txtidate.setText("");
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new Books().setVisible(true);
            } catch (Exception ex) {
               java.util.logging.Logger.getLogger(IssueBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        });
    }
    private void searchbook() {
        try {
            String Bid = tblissuebook.getValueAt(tblissuebook.getSelectedRow(), 0).toString();
            IssuebookDto dto = issueBookController.get(Bid);

            if (dto != null) {
                txtbid.setText(dto.getBid());
                txtmid.setText(dto.getMid());
                txtrdate.setText(dto.getRdate());
                txtidate.setText(dto.getIdate());
            } else {
                JOptionPane.showMessageDialog(this, "book Not Found");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error at loading book");
        }
    }
    
    private void deletebook(){
        try {
            String Bid = txtbid.getText();
            String resp = issueBookController.delete(Bid);
            JOptionPane.showMessageDialog(this, resp);
            clearForm();
            loadTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error at Delete book");
        }
    }

    private void updatebook() {
        try {
            IssuebookDto issuebookDto = new IssuebookDto(txtbid.getText() , txtmid.getText(),txtrdate.getText(), txtidate.getText());
            String resp = issueBookController.update(issuebookDto);
            JOptionPane.showMessageDialog(this, resp);
            loadTable();
            clearForm();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error at update book");
        }
    }
}

